cc_test(
    name = "sparse_table_test",
    srcs = [
        "sparse_table_test.cc",
        "//core/utility:random",
    ],
    deps = [
        "//core:_ps_table",
        "@brpc//:brpc",
        "@com_google_googletest//:gtest_main",
    ],
    copts = ["-g -ggdb"],
)
