cc_test(
    name = "allocator_test",
    srcs = [
        "allocator_test.cc"
    ],
    deps = [
        "//core:_core_lib",
        "@com_google_googletest//:gtest_main",
    ],
    copts = ["-g -ggdb"],
)
